# Generated by Django 3.0.8 on 2020-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='yjf',
            fields=[
                ('user', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'yjf',
            },
        ),
    ]
